Repository bangmod-hackathon/bmhk2024-2, pull requests merged in 2024-07, with the labels that each got.

#30 Feat(registration step)
  src/App.tsx
  src/components/Steps/Stage.css
  src/components/Steps/Stage.tsx
Labels: registration, ready to review

#32 Feat(scope)
  .eslintrc.cjs
  public/Confirm_icon/AiTwotoneCheckCircle.png
  public/ScopeContentPDF/ขอบเขตเนื้อหาที่ใช้ในการแข่งขัน.pdf
  public/diamon_img/Angle-double.png
  public/diamon_img/gem3-blue.png
  public/diamon_img/gem4-blue.png
  public/diamon_img/gem5-red.png
  src/App.tsx
  src/components/CategoryCard.tsx
  src/components/Modal/ComfirmModal.tsx
  src/components/Modal/GenericModal.tsx
  src/components/Modal/ModalAlgorithm.tsx
  src/components/Modal/ModalComSci.tsx
  src/components/Modal/ModalMath.tsx
  src/components/Scope.tsx
  src/components/Scope_Content/AlgorithmContent.tsx
  src/components/Scope_Content/ComSciContent.tsx
  src/components/Scope_Content/CustomScrollBar.css
  src/components/Scope_Content/MathContent.tsx
  tailwind.config.js
Labels: landing

#31 Feat(rewards) - finished
  public/img/chest1.png
  public/img/chest1_hover.png
  public/img/chest2.png
  public/img/chest2_hover.png
  public/img/chest3.png
  public/img/chest3_hover.png
  src/components/Rewards.tsx
  src/index.css
  yarn.lock
Labels: landing

#29 feat: Docs & Qualifications for desktop view
  public/images/student2.png
  public/images/student4.png
  public/images/teacher.png
  src/components/Docs.tsx
  src/components/Qualifications.tsx
  src/images/student2.png
  src/images/student4.png
  src/images/teacher.png
Labels: landing, ready to review

#27 feat : upload component
  package.json
  src/App.tsx
  src/components/Form/Upload.tsx
  src/constants/errorMessage.ts
  src/index.css
  src/utils/utils.ts
  tailwind.config.js
  yarn.lock
Labels: registration

#34 [App]: Router
  package.json
  src/App.tsx
  src/components/Hero/Hero.tsx
  src/components/Hero/fade.css
  src/main.tsx
  src/pages/LandingPage.tsx
  yarn.lock
Labels: technical improvement, ready to review, ready to merge

#35 feat: create footer
  .eslintrc.cjs
  src/components/Footer.tsx
  src/pages/LandingPage.tsx
Labels: landing, ready to review, ready to merge

#39 feat: navbar-scroll
  package.json
  src/components/Docs.tsx
  src/components/Footer.tsx
  src/components/Hero/Hero.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Qualifications.tsx
  src/components/Rewards.tsx
  src/components/Scope.tsx
  src/pages/LandingPage.tsx
  yarn.lock
Labels: enhancement, landing, ready to review, ready to merge

#44 Fix(add navigation to timeline component)
  src/pages/LandingPage.tsx
  yarn.lock
Labels: enhancement, landing, ready to review, ready to merge

#46 fix : background not found when build
  src/components/Timeline/Timeline.tsx
  src/pages/LandingPage.tsx
Labels: bug, landing, ready to review

#47 fix(footer): sponsor
  public/footer/advice.webp
  public/footer/honda.webp
  public/footer/hp.webp
  public/footer/line.webp
  public/footer/nasa.webp
  src/components/Footer.tsx
Labels: landing, ready to review

#48 Feat(auth)
  package.json
  src/App.tsx
  src/components/Docs.tsx
  src/components/Hero/Hero.tsx
  src/components/Login/LoginForm.tsx
  src/components/Qualifications.tsx
  src/components/Rewards.tsx
  src/components/Scope.tsx
  src/contexts/authContext.ts
  src/interfaces/user.interface.ts
  src/utils/axios.ts
  yarn.lock
Labels: enhancement, ready to review
