Repository bangmod-hackathon/bmhk2024-2, pull requests merged in 2024-08, with the labels that each got.

#41 Feat(registration form template)
  src/components/Form/Input.tsx
  src/components/Form/Input/Input.tsx
  src/components/Form/Input/Select.tsx
  src/components/Form/Input/TextArea.tsx
  src/components/Form/ParticipantContactsForm.tsx
  src/components/Form/ParticipantForm.tsx
  src/components/Form/TeacherContactsForm.tsx
  src/components/Form/TeacherForm.tsx
  src/components/Form/TeamForm.tsx
  src/index.css
  src/lib/ThemeProvider.tsx
  src/lib/antdForm.tsx
Labels: registration

#50 Feat: Team and Teacher Form
  public/register/bg-register.webp
  src/App.tsx
  src/components/Form/TeacherDocsForm.tsx
  src/components/Form/TeamTeacherStepForm.tsx
  src/components/Form/Upload.tsx
  src/components/Navbar/Navbar.tsx
  src/contexts/AuthContext.tsx
  src/pages/ConsentPage.tsx
  src/pages/LandingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterFormStep.tsx
Labels: registration

#51 feat : participant form
  src/components/Form/PageChanger.tsx
  src/components/Form/ParticipantDocsForm.tsx
  src/components/Form/ParticipantForm.tsx
  src/components/Form/ParticipantStepForm.tsx
  src/components/Form/TeamForm.tsx
  src/components/Form/TeamTeacherStepForm.tsx
  src/components/Modal/ComfirmModal.tsx
  src/components/Scope.tsx
  src/pages/RegisterFormStep.tsx
Labels: registration, ready to review

#52 feat : stage changer
  src/components/Steps/Stage.tsx
  src/pages/RegisterFormStep.tsx
Labels: registration, ready to review

#55 fix : login navbar not rendering in first time
  src/components/Navbar/Navbar.tsx
Labels: bug, technical improvement

#62 Patch data
  .env.example
  .gitignore
  src/components/Form/PageChanger.tsx
  src/components/Form/ParticipantContactsForm.tsx
  src/components/Form/ParticipantDocsForm.tsx
  src/components/Form/ParticipantForm.tsx
  src/components/Form/ParticipantStepForm.tsx
  src/components/Form/TeacherContactsForm.tsx
  src/components/Form/TeacherDocsForm.tsx
  src/components/Form/TeacherForm.tsx
  src/components/Form/TeamForm.tsx
  src/components/Form/TeamTeacherStepForm.tsx
  src/components/Login/LoginForm.tsx
  src/components/Modal/ComfirmModal.tsx
  src/contexts/AuthContext.tsx
  src/interfaces/user.interface.ts
  src/pages/RegisterFormStep.tsx
  src/utils/axios.ts
Labels: enhancement, registration, ready to merge

#65 feat | upload
  package.json
  src/components/Consent/ConsentForm.tsx
  src/components/Form/PageChanger.tsx
  src/components/Form/ParticipantContactsForm.tsx
  src/components/Form/ParticipantDocsForm.tsx
  src/components/Form/ParticipantStepForm.tsx
  src/components/Form/TeacherContactsForm.tsx
  src/components/Form/TeacherDocsForm.tsx
  src/components/Form/TeamForm.tsx
  src/components/Form/TeamTeacherStepForm.tsx
  src/components/Form/Upload.tsx
  src/components/Modal/ComfirmModal.tsx
  src/components/Navbar/Navbar.tsx
  src/constants/errorMessage.ts
  src/interfaces/user.interface.ts
  src/pages/ConsentPage.tsx
  src/pages/RegisterFormStep.tsx
  src/utils/firebase.ts
  src/utils/uploadFile.ts
  yarn.lock
Labels: registration, ready to review, ready to merge
